### PR TITLE
Translated into Spanish

### PR DESCRIPTION
**Pull request by b3cl0s3r**
SUMMARY.md , README.md , introduction/architecture.md and introduction/motivation.md were translated into Spanish. 

Please, check if you see it was well done. If not, please, give me a feedback to improve for the next pull request. 

Should directories and files be translated into Spanish?

Thanks!

### CODE REVIEW

**Comment by bkimminich** [comment]
You should add your name in the README here:

```
Traducido al español por ...
```

**Comment by bkimminich** [comment]
Translating file names or directories will make any attempts to follow up with updated content in the original... I wouldn't recommend it.

**Comment by b3cl0s3r** [comment]
Thanks! That change has been already done. I'll keep translating the rest of the book :)

**Comment by bkimminich** [comment]
@CarlosAllendes please review and merge if all is fine. Gracias!

**Comment by CarlosAllendes** [comment]
Ok Bjorn...

Im looking the changes to make the best merge.

HOLA becloser..  de donde eres?

---------
Saludos Cordiales
Carlos Allendes D.
pdte. Owasp Chile
cell.:+56951264364
=================

**Comment by b3cl0s3r** [comment]
¡Hola!
De Tenerife (Islas Canarias, España)

**Comment by CarlosAllendes** [comment]
---------
Saludos Cordiales
Carlos Allendes D.
pdte. Owasp Chile
cell.:+56951264364
=================

**Comment by b3cl0s3r** [comment]
No he estado nada pendiente del Pull Request debido a los exámenes, pero en principio los arreglos que me comentaste deberían estar ya pusheados del commit de hace 17 días. ¡Un saludo!

**Comment by CarlosAllendes** [comment]
Holaaaa

Yo estoy crazy  recorriendo Chile haciendo charlas para organizar este
recorrido   de hacking turistico

https://www.owasp.org/index.php/Chile#tab=Iron_Hacker_Tour

---------
Saludos Cordiales
Carlos Allendes D.
pdte. Owasp Chile
cell.:+56951264364
=================

**Pull request merged**
